/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsuariosIndexRouteImport } from './routes/usuarios/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CadastroIndexRouteImport } from './routes/cadastro/index'
import { Route as AtivosIndexRouteImport } from './routes/ativos/index'
import { Route as ErrorsCompanyNotFoundRouteImport } from './routes/errors/companyNotFound'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIndexRoute = UsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroIndexRoute = CadastroIndexRouteImport.update({
  id: '/cadastro/',
  path: '/cadastro/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivosIndexRoute = AtivosIndexRouteImport.update({
  id: '/ativos/',
  path: '/ativos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsCompanyNotFoundRoute = ErrorsCompanyNotFoundRouteImport.update({
  id: '/errors/companyNotFound',
  path: '/errors/companyNotFound',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/errors/companyNotFound': typeof ErrorsCompanyNotFoundRoute
  '/ativos/': typeof AtivosIndexRoute
  '/cadastro/': typeof CadastroIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/errors/companyNotFound': typeof ErrorsCompanyNotFoundRoute
  '/ativos': typeof AtivosIndexRoute
  '/cadastro': typeof CadastroIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/usuarios': typeof UsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/errors/companyNotFound': typeof ErrorsCompanyNotFoundRoute
  '/ativos/': typeof AtivosIndexRoute
  '/cadastro/': typeof CadastroIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/errors/companyNotFound'
    | '/ativos/'
    | '/cadastro/'
    | '/dashboard/'
    | '/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/errors/companyNotFound'
    | '/ativos'
    | '/cadastro'
    | '/dashboard'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/errors/companyNotFound'
    | '/ativos/'
    | '/cadastro/'
    | '/dashboard/'
    | '/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ErrorsCompanyNotFoundRoute: typeof ErrorsCompanyNotFoundRoute
  AtivosIndexRoute: typeof AtivosIndexRoute
  CadastroIndexRoute: typeof CadastroIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  UsuariosIndexRoute: typeof UsuariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/': {
      id: '/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof UsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/': {
      id: '/cadastro/'
      path: '/cadastro'
      fullPath: '/cadastro/'
      preLoaderRoute: typeof CadastroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativos/': {
      id: '/ativos/'
      path: '/ativos'
      fullPath: '/ativos/'
      preLoaderRoute: typeof AtivosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/companyNotFound': {
      id: '/errors/companyNotFound'
      path: '/errors/companyNotFound'
      fullPath: '/errors/companyNotFound'
      preLoaderRoute: typeof ErrorsCompanyNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  ErrorsCompanyNotFoundRoute: ErrorsCompanyNotFoundRoute,
  AtivosIndexRoute: AtivosIndexRoute,
  CadastroIndexRoute: CadastroIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  UsuariosIndexRoute: UsuariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
